export const ENGLISH_MONTHS = {
	January: 'Enero',
	Jan: 'Enero',
	February: 'Febrero',
	Feb: 'Febrero',
	March: 'Marzo',
	Mar: 'Marzo',
	April: 'Abril',
	Apr: 'Abril',
	May: 'Mayo',
	June: 'Junio',
	Jun: 'Junio',
	July: 'Julio',
	Jul: 'Julio',
	August: 'Agosto',
	Aug: 'Agosto',
	September: 'Septiembre',
	Sep: 'Septiembre',
	October: 'Octubre',
	Oct: 'Octubre',
	November: 'Noviembre',
	Nov: 'Noviembre',
	December: 'Diciembre',
	Dec: 'Diciembre',
};
